[build]
  command = "npm run build"
  functions = "netlify/functions"  
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  DATABASE_URL = "postgresql://neondb_owner:npg_iof5LtlVy7eY@ep-shiny-breeze-ae06mvuz-pooler.c-2.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
  GOOGLE_PLACES_API_KEY = "AIzaSyDtR2sZLXQ4l-P33jS70r9OEQFStSa3ikA"
  GOOGLE_MAPS_API_KEY = "AIzaSyDtR2sZLXQ4l-P33jS70r9OEQFStSa3ikA"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon", "bcryptjs", "jsonwebtoken"]
  included_files = ["**"]

[dev]
  command = "npm run dev:vite"
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

# Environment variables (will be injected from Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.dev.environment] 
  NODE_ENV = "development"

# Function routing for path parameters (removed due to syntax errors)
