[build]
  command = "npm run prebuild && npm run build && node scripts/optimize-deploy.mjs"
  functions = "netlify/functions"  
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  DATABASE_URL = "postgresql://neondb_owner:npg_iof5LtlVy7eY@ep-shiny-breeze-ae06mvuz-pooler.c-2.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
  GOOGLE_PLACES_API_KEY = "AIzaSyDtR2sZLXQ4l-P33jS70r9OEQFStSa3ikA"
  GOOGLE_MAPS_API_KEY = "AIzaSyDtR2sZLXQ4l-P33jS70r9OEQFStSa3ikA"
  JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "@netlify/neon", "bcryptjs", "jsonwebtoken"]
  included_files = ["data/**"]

[dev]
  command = "npm run dev:vite"
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

# Environment variables (will be injected from Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.dev.environment] 
  NODE_ENV = "development"

# Function routing for path parameters (removed due to syntax errors)
